### ISSUE TITLE
As a novice user, I'd like to be able too have a help desk so I can ask for help if I need

### ISSUE THREAD

**Issue by Eric-Philippe** [IUT-Blagnac-3A/SAE-ALT-S3-Dev-22-23-CaptElec-3A-Equipe-2#76]
## Estimation of effort
Low

## Acceptance Criteria
- [ ] - Having a help page [Linked Issue](https://github.com/IUT-Blagnac-3A/SAE-ALT-S3-Dev-22-23-CaptElec-3A-Equipe-2/issues/58)
- [ ]  - Being able to have short reach help documents for the first help [Linked Issue](https://github.com/IUT-Blagnac-3A/SAE-ALT-S3-Dev-22-23-CaptElec-3A-Equipe-2/issues/58)
- [ ]  - Having documents explaning the different features of the website [Linked Issue](https://github.com/IUT-Blagnac-3A/SAE-ALT-S3-Dev-22-23-CaptElec-3A-Equipe-2/issues/58)
